# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/tan/edadesign/Vivado/flow_led/flow_led.cache/wt [current_project]
set_property parent.project_path E:/tan/edadesign/Vivado/flow_led/flow_led.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/tan/edadesign/Vivado/flow_led/flow_led.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/tan/edadesign/Vivado/flow_led/flow_led.srcs/sources_1/new/flow_led.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/tan/edadesign/Vivado/flow_led/flow_led.srcs/constrs_1/new/flow_led.xdc
set_property used_in_implementation false [get_files E:/tan/edadesign/Vivado/flow_led/flow_led.srcs/constrs_1/new/flow_led.xdc]


synth_design -top flow_led -part xc7a35tcsg324-1


write_checkpoint -force -noxdef flow_led.dcp

catch { report_utilization -file flow_led_utilization_synth.rpt -pb flow_led_utilization_synth.pb }
